version: '3'

services:
  laravel:
    image: cristiano23lima/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    image: cristiano23lima/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"
networks:
  laranet:
    driver: bridge